### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by pbalduino** [guru-sp/wyrdbot#1]
I'm doing something run and cannot run here.

./bin/../lib/simple_bot/google_services.rb:3:in `require': no such file to load -- json (LoadError)
    from ./bin/../lib/simple_bot/google_services.rb:3
    from ./bin/../lib/simple_bot.rb:2:in`require'
    from ./bin/../lib/simple_bot.rb:2
    from bin/bot.rb:3:in `require'
    from bin/bot.rb:3

The JSON stuff is already installed.

**Comment by PotHix** [comment]
Ruby 1.9 already have a native Json implementation. In my conception all Rubyists are using Ruby 1.9.x when possible...I don't know why we need to use 1.8.x =/

If we really need to do this, this issue will be fixed adding json gem to Gemfile.

**Comment by pbalduino** [comment]
Adding json via Gemfile doesn't work.
I added a conditional require and tested with 1.8.7 and 1.9.2. With 1.9.2 it worked fine.
I won't test again with 1.8.x after that.
